name = "pinkdf2"
version = "2.0.0"

description = "Gleam bindings to fast_pbkdf2 NIF of PBKDF2 (Password-Based Key Derivation Function 2) for Erlang."
licences = ["Apache-2.0"]
repository = { type = "github", user = "yazatamorph", repo = "pinkdf2" }
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
fast_pbkdf2 = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
